# Generated by Django 3.1.3 on 2020-12-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlastJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlastResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_no', models.IntegerField()),
                ('sstart', models.IntegerField()),
                ('send', models.IntegerField()),
                ('sstrand', models.CharField(max_length=5)),
                ('evalue', models.FloatField()),
                ('pident', models.FloatField()),
                ('sequence', models.CharField(max_length=255)),
                ('blast_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast.blastjob')),
            ],
        ),
    ]
